[package]
name = "fx-test-app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlx = { version = "0.8.5", default-features = false }
fx = { path = "../../fx"}
fx-utils = { path = "../../fx-utils" }
