[package]
name = "fx-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-rs-async-executor = "0.9.0"
axum = { version = "0.8.3", default-features = false }
tower = "0.5.2"
futures = "0.3.31"

fx = { path = "../fx" }
