[package]
name = "fx-app-mocks"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.8.4", default-features = false }

fx = { path = "../fx" }
fx-utils = { path = "../fx-utils" }
