[package]
name = "fx-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
http = "1.3.1"
http-serde = "2.1.1"
thiserror = "2.0.12"
serde_json = "1.0.140"
urlencoding = "2.1.3"
